# 1

In [3]:
import numpy as np
npmattrix = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(nparray)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# 2

In [ ]:
import numpy as np
array2 = np.random.rand(6)
print("Array initialized with Random value :",array2)

# 3

In [8]:
matrix3 = np.array([[1,2],[3,4]])
print("Matrix is :")
print(matrix3)
print("")
print("Determinant Of Matrix is :")
print(np.linalg.det(matrix3));
print()
print("Transpose of Matrix is:")
print((matrix3).T)

Matrix is :
[[1 2]
 [3 4]]

Determinant Of Matrix is :
-2.0000000000000004

Transpose of Matrix is:
[[1 3]
 [2 4]]


# 4

In [3]:
import numpy as np
matrix4 = np.random.rand(5,4)
print("Array initialized with Random value :\n",matrix4)

Array initialized with Random value :
 [[0.25649477 0.82465299 0.98346831 0.77244239]
 [0.1250935  0.35146256 0.93335325 0.88239511]
 [0.87791797 0.55706242 0.67653723 0.73831359]
 [0.29843223 0.86946489 0.99789865 0.67497425]
 [0.55570806 0.23402153 0.29262495 0.77575155]]


# 5

In [4]:
matrix41 = np.array([[1,2],[3,4]])
matrix42 = np.array([[5,6],[7,8]])
print(np.dot(matrix41,matrix42))

[[19 22]
 [43 50]]


# 6

In [12]:
matrix51 = np.array([[1,2],[3,4]])
matrix52 = np.array([[5,6],[7,8]])
print(np.multiply(matrix51,matrix52))

[[ 5 12]
 [21 32]]


# 7

In [8]:
matrix7 = np.array([[2,2,3],[3,4,5]])
print(np.mean(matrix7))
print(np.median(matrix7))

3.1666666666666665
3.0


# 8

In [13]:
matrix8 = np.array([[2,3,5],[7,11,13],[17,19,23]])
print(matrix8[0:,1])

[ 3 11 19]


# 9

In [3]:
import pandas as pd
iris = pd.read_csv('iris.csv')
print(iris.mean())

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64


# 10

In [6]:
import numpy as np 
a = np.array([[1,2,3,4],[3,4,5,6]]) 
print (a.shape)
b= a.reshape(4,2)
print(b)

(2, 4)
[[1 2]
 [3 4]
 [3 4]
 [5 6]]
