In [ ]:
# @author - Nikhil Bambhroliya

#Linear regression model from scratch

In [95]:
import numpy as np
import torch

In [81]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [82]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [83]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [84]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [85]:
inputs @ weight.t() + bias

tensor([[ -73.3656,  -98.3297],
        [ -92.2246, -142.0584],
        [-139.1011, -222.6786],
        [ -59.5573,  -20.0133],
        [ -92.0101, -184.5744]], grad_fn=<AddBackward0>)

In [86]:
def model(inputs):
    return inputs @ weight.t() + bias

In [87]:
prediction = model(inputs)
print(prediction)

tensor([[ -73.3656,  -98.3297],
        [ -92.2246, -142.0584],
        [-139.1011, -222.6786],
        [ -59.5573,  -20.0133],
        [ -92.0101, -184.5744]], grad_fn=<AddBackward0>)


##Loss function

In [88]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(43282.0078, grad_fn=<DivBackward0>)

In [89]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [90]:
loss = mse(prediction, targets)
print(loss)

tensor(43282.0078, grad_fn=<DivBackward0>)


##Compute gradients

In [91]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[-13887.2930, -16144.9492,  -9657.4570],
        [-17083.6816, -21033.5762, -12482.7949]])
tensor([-167.4517, -209.7309])


##Train the model using gradient descent

In [92]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [97]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(21364.4121, grad_fn=<DivBackward0>)


In [100]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [101]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(913.8755, grad_fn=<DivBackward0>)


In [102]:
prediction

tensor([[62.2296, 69.7153],
        [88.4226, 85.4121],
        [96.4126, 91.2257],
        [51.4243, 93.9224],
        [94.8999, 64.9022]], grad_fn=<AddBackward0>)

In [103]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])