In [ ]:
# @author - Nikhil Bambhroliya 

In [3]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

In [2]:
weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [3]:
le = LabelEncoder()

weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
class_label = le.fit_transform(play)

print("Weather :\n", weather_encoded)
print("\nTemperature :\n", temp_encoded)
print("\nPlay :\n", class_label)

Weather :
 [2 2 0 1 1 1 0 2 2 1 2 0 0 1]

Temperature :
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]

Play :
 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [4]:
features = tuple(zip(weather_encoded, temp_encoded))

print("Features :\n", features)

Features :
 ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [5]:
model = MultinomialNB()
model.fit(features, class_label)

MultinomialNB()

In [6]:
predicted = model.predict_proba([[2,2]])
print("Weather is Sunny, Temp is Mild =", predicted)

Weather is Sunny, Temp is Mild = [[0.36151612 0.63848388]]


In [7]:
iris=datasets.load_iris()

print("Features :\n", iris.feature_names)
print("\nLabels :\n", iris.target_names)

print("\nData shape : ", iris.data.shape)
print("\nTraget shape : ", iris.target.shape)

# print("\nData :\n", iris.data)
# print("\nTarget :\n", iris.target)

print("\nData type : ", type(iris.data))

newdata = iris.data[50: , :]
newtarget = iris.target[50:]

print("\nNew Data shape : ", newdata.shape)
print("\nNew Traget shape : ", newtarget.shape)

Features :
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels :
 ['setosa' 'versicolor' 'virginica']

Data shape :  (150, 4)

Traget shape :  (150,)

Data type :  <class 'numpy.ndarray'>

New Data shape :  (100, 4)

New Traget shape :  (100,)


In [8]:
data_train, data_test, target_train, target_test = train_test_split(newdata, newtarget, test_size = 0.30, random_state = 9)

gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

print("Accuracy :", metrics.accuracy_score(target_test, target_pred))
print("\nConfusion Matrix :\n", confusion_matrix(target_test, target_pred))

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)

print('\nprecision :', precision)
print('\nrecall :', recall)

Accuracy : 0.9333333333333333

Confusion Matrix :
 [[17  1]
 [ 1 11]]

precision : 0.9444444444444444

recall : 0.9444444444444444


# Task 1: 
Try the algo on Dataset1 - OneHotEncoding of features: and Train test Division 70%-30%

In [67]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
data=pd.read_csv('Dataset1.csv')
print(data)

   Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N


In [65]:

o=data['Outlook']
outlook=pd.get_dummies(o)
t=data['Temp']
temp=pd.get_dummies(t)
h=data['Humidity']
humidity=pd.get_dummies(h)
w=data['Wind']
wind=pd.get_dummies(w)
le=LabelEncoder()
data.iloc[:,-1]=le.fit_transform(data['Play'])

data = data.drop(['Outlook', 'Temp', 'Humidity', 'Wind'], axis = 1)
data = pd.concat([outlook, temp, humidity, wind, data], axis = 1)

print("encoded data: \n",data)

encoded data: 
     O  R  S  C  H  M  High  Low  Normal  F  T  Play
0   0  1  0  0  1  0     0    0       1  1  0     0
1   0  1  0  0  1  0     1    0       0  0  1     0
2   1  0  0  0  1  0     0    0       1  1  0     1
3   0  0  1  0  0  1     0    0       1  1  0     1
4   0  0  1  1  0  0     0    0       1  1  0     1
5   0  0  1  1  0  0     0    1       0  0  1     0
6   1  0  0  1  0  0     0    0       1  0  1     1
7   0  1  0  0  0  1     0    0       1  1  0     0
8   0  1  0  1  0  0     0    1       0  1  0     1
9   0  0  1  0  0  1     1    0       0  1  0     1
10  0  1  0  0  0  1     1    0       0  0  1     1
11  1  0  0  0  0  1     0    1       0  0  1     1
12  1  0  0  0  1  0     0    0       1  1  0     1
13  0  0  1  0  0  1     0    0       1  0  1     0


In [66]:
features=data.iloc[:,:-1]
labels=data.iloc[:,-1]
print("Features : \n",features)

Features : 
     O  R  S  C  H  M  High  Low  Normal  F  T
0   0  1  0  0  1  0     0    0       1  1  0
1   0  1  0  0  1  0     1    0       0  0  1
2   1  0  0  0  1  0     0    0       1  1  0
3   0  0  1  0  0  1     0    0       1  1  0
4   0  0  1  1  0  0     0    0       1  1  0
5   0  0  1  1  0  0     0    1       0  0  1
6   1  0  0  1  0  0     0    0       1  0  1
7   0  1  0  0  0  1     0    0       1  1  0
8   0  1  0  1  0  0     0    1       0  1  0
9   0  0  1  0  0  1     1    0       0  1  0
10  0  1  0  0  0  1     1    0       0  0  1
11  1  0  0  0  0  1     0    1       0  0  1
12  1  0  0  0  1  0     0    0       1  1  0
13  0  0  1  0  0  1     0    0       1  0  1


In [69]:
data_train,data_test,tar_train,tar_test=train_test_split(features,labels,test_size=0.30,random_state=60)

gnd=GaussianNB()

gnd.fit(data_train,tar_train)
tar_pred=gnd.predict(data_test)
print("Accuracy :",metrics.accuracy_score(tar_test,tar_pred))

print("\nConfusion Matrix :\n", confusion_matrix(tar_test, tar_pred))

precision = precision_score(tar_test, tar_pred)
recall = recall_score(tar_test, tar_pred)

print('\nprecision :', precision)
print('\nrecall :', recall)

Accuracy : 0.6

Confusion Matrix :
 [[1 1]
 [1 2]]

precision : 0.6666666666666666

recall : 0.6666666666666666


# TASK2
Apply algorithm on digits dataset - LabelEncoding of features: and Train test Division 80%-20%

In [87]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv("abalone_train.csv",names=["Length", "Diameter", "Height", "Weight", "Age"])
data

Length  Diameter  Height  Weight  Age
0       5         4       4       2   18
1       6         5       3       3   10
2       4         6       2       5   10
3       3         2       1       6   18
4       4         4       2       6   10
5       5         2       3       5   18
6       6         6       1       3   18
7       4         5       4       2   18
8       3         2       2       2   10

In [88]:
le=LabelEncoder()
length=le.fit_transform(data.Length)
print("\nlength :",data.Length)
print("\nEncoded length :",length)

diameter=le.fit_transform(data.Diameter)
print("\ndiameter :",data.Diameter)
print("\nEncoded diameter :",diameter)

height=le.fit_transform(data.Height)
print("\nheight :",data.Height)
print("\nEncoded height :",height)

weight=le.fit_transform(data.Weight)
print("\nweight :",data.Weight)
print("\nEncoded weight :",weight)

res=le.fit_transform(data.Age)
print("\nage :",data.Age)
print("\nEncoded age :",res)



length : 0    5
1    6
2    4
3    3
4    4
5    5
6    6
7    4
8    3
Name: Length, dtype: int64

Encoded length : [2 3 1 0 1 2 3 1 0]

diameter : 0    4
1    5
2    6
3    2
4    4
5    2
6    6
7    5
8    2
Name: Diameter, dtype: int64

Encoded diameter : [1 2 3 0 1 0 3 2 0]

height : 0    4
1    3
2    2
3    1
4    2
5    3
6    1
7    4
8    2
Name: Height, dtype: int64

Encoded height : [3 2 1 0 1 2 0 3 1]

weight : 0    2
1    3
2    5
3    6
4    6
5    5
6    3
7    2
8    2
Name: Weight, dtype: int64

Encoded weight : [0 1 2 3 3 2 1 0 0]

age : 0    18
1    10
2    10
3    18
4    10
5    18
6    18
7    18
8    10
Name: Age, dtype: int64

Encoded age : [1 0 0 1 0 1 1 1 0]


In [89]:
features=(tuple)(zip(length,diameter,height,weight))
print("Features : ",features)

Features :  ((2, 1, 3, 0), (3, 2, 2, 1), (1, 3, 1, 2), (0, 0, 0, 3), (1, 1, 1, 3), (2, 0, 2, 2), (3, 3, 0, 1), (1, 2, 3, 0), (0, 0, 1, 0))


In [90]:
model=GaussianNB()
model.fit(features,res);

predict=model.predict([[0,2,0,2],[1,0,3,0]])
print("Predicted :",predict)

Predicted : [1 1]


### Accuracy

In [91]:
data_train,data_test,tar_train,tar_test=train_test_split(features,res,test_size=0.20,random_state=60)

In [92]:
gnd=GaussianNB()
gnd.fit(data_train,tar_train)
tar_pred=gnd.predict(data_test)
print("Accuracy :",metrics.accuracy_score(tar_test,tar_pred))

Accuracy : 0.5


In [93]:
print("Confusion Metrix: ",confusion_matrix(tar_test, tar_pred))

Confusion Metrix:  [[0 1]
 [0 1]]


In [94]:
pricision=precision_score(tar_test, tar_pred,average=None)
recall=recall_score(tar_test, tar_pred,average=None)
print("Pricision : {}".format(pricision))
print("Recall : {}".format(recall))

Pricision : [0.  0.5]
Recall : [0. 1.]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
